server:
  port : 8080

  # Database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usertestdb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Saleem@27
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect