spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/fassciodb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password:
#    password: Saleem@27
    password: ENC(dmIRdpSRscZCQvOiTTNN49UR3SWKSgjaOMfwyY02k81+RK1C3EQmQ3FR4Gc65EvQ)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  token-validity-in-seconds: 25920000
  

string:
  exceptionValue: Required request body is missing